CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(500) NOT NULL,
  available BOOLEAN NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT pk_items PRIMARY KEY (id),
  CONSTRAINT fk_items_user_id_users_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP(0) NOT NULL,
  end_date TIMESTAMP(0) NOT NULL,
  item_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  status VARCHAR(8) NOT NULL,
  CONSTRAINT pk_bookings PRIMARY KEY (id),
  CONSTRAINT fk_bookings_item_id_items_id FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_bookings_user_id_users_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR NOT NULL,
  item_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created TIMESTAMP(0) NOT NULL,
  CONSTRAINT pk_comments PRIMARY KEY (id),
  CONSTRAINT fk_comments_item_id_items_id FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_comments_user_id_users_id FOREIGN KEY (user_id) REFERENCES users(id)
);